# Generated by Django 5.2.3 on 2025-07-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_company_user_alter_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business')], default='Personal', max_length=10),
        ),
    ]
